sudo: false
addons:
  apt:
    packages:
    - net-tools

cache: bundler
language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler ${BUNDLER_VERSION:+-v} ${BUNDLER_VERSION}
  - bundle --version
  - mkdir -p tmp/bundle

bundler_args: "--binstubs"

script: ./test/test_with_railsapp

matrix:

  include:

    # Temporary version lock until Bundler >= 1.13.2
    # https://github.com/bundler/bundler/issues/4975
    - rvm: jruby-19mode
      gemfile: test/rails_4.2.gemfile
      env: BUNDLER_VERSION=1.12.5 RAILS_VERSION=4.2

