language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler
  - bundle --version
  - mkdir -p tmp/bundle

bundler_args: "--binstubs"

script: ./test/test_with_railsapp

matrix:
  allow_failures:
    - rvm: 1.8.7
      gemfile: test/rails_2.3_lts.gemfile
      env: RUBYGEMS_VERSION=1.8.25 RAILS_VERSION=2.3

  include:
    # rails 2.3 march 16 2009 - ruby 1.8.7
    # railslts.com
    - rvm: 1.8.7
      gemfile: test/rails_2.3_lts.gemfile
      env: RUBYGEMS_VERSION=1.8.25 RAILS_VERSION=2.3

    - rvm: 1.8.7
      gemfile: test/rails_2.3.gemfile
      env: RUBYGEMS_VERSION=1.8.25 RAILS_VERSION=2.3

